### ISSUE TITLE
[joss] update entry site of the documentation

### ISSUE THREAD

**Issue by hbaniecki** [sergioburdisso/pyss3#18]
https://github.com/openjournals/joss-reviews/issues/3934

Hi, I enjoy working with http://tworld.io/ss3, which is highlighted in README. It is also good to see a statement of need with the two references there. Could we add the same to the welcome page of the documentation at https://pyss3.readthedocs.io/en/latest?

**Comment by sergioburdisso** [comment]
Hi @hbaniecki! I'm glad to hear you enjoy the live demo! :blush:

Thanks for this suggestion, I've just updated the ``README.md`` to add to more references and also added the same state of need to the welcome page of the documentations as you suggested. Thank you for helping me to improve this project!  :octocat:
