### ISSUE TITLE
Error in Live_test

### ISSUE THREAD

**Issue by penatbater** [sergioburdisso/pyss3#2]
I'm getting an error list index out of range. I'm not sure what happened here. I'm using the latest built as of posting (just installed it prior to using it here), my python is 3.6 if I remember correctly.
![image](https://user-images.githubusercontent.com/37921244/77934434-a8e55a80-72e2-11ea-9d87-9938d3a8c6a6.png)

EDIT: I don't know why but restarting the kernel fixed it.

**Comment by penatbater** [comment]
Ok no sorry it keeps coming back. I'm not sure what I did before to get it to run.

**Comment by sergioburdisso** [comment]
Hi @penatbater taking a look at the code I think I've found what could be causing  the problem, I'll do some changes and I'll release a new version today so you can see if it fixed the problem, It won't take too much time :+1:

**Comment by sergioburdisso** [comment]
Hi again @penatbater, I've just released the new version, try updating pyss3 (pip install -U pyss3) to the newer version (0.5.6) and see if the changes I've made have fixed your problem. Let me know if it worked :+1:

**Comment by penatbater** [comment]
@sergioburdisso Thanks very much! Can confirm it now works. :)

**Comment by sergioburdisso** [comment]
That-s great!! Thanks for helping to make this project better! :)
